---
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - docker-dev.env
    depends_on:
      - db
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /usr/src/app
          initial_sync: true
          ignore:
            - .venv
            - tavern
            - scripts
            - Dockerfile
            - config

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-compose
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    command: /app/scripts/entrypoint-compose.sh
    depends_on:
      - backend

  db:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - ./.dev-data/roombaht-postgres:/var/lib/postgresql/data
    env_file:
      - docker-dev.env
